### ISSUE TITLE
tag the example images

### ISSUE THREAD

**Issue by saturnism** [redhat-developer-demos/kubernetes-lab#3]
i noticed that the guestbook service image, and the frontend image are both using the "latest" tags.

kubernetes will automatically mark the deployment to always pull images when using the latest tag. this could slowdown future deployment.

but most importantly, the "always" policy will be applied when using `kubectl edit deployment ...` unless changed otherwise.

**Comment by rafabene** [comment]
Besides https://github.com/redhat-developer-demos/kubernetes-lab/blob/master/kubernetes/mysql-rc.yaml, all of them are now tagged.
